"""add embedding column to policy_chunks

Revision ID: 49c55d02b1f4
Revises: eeb809b56710
Create Date: 2025-06-09 13:58:39.245358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c55d02b1f4'
down_revision = 'eeb809b56710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_source_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_policy_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_document_gcs_path', sa.String(length=255), nullable=False),
    sa.Column('processed_json_gcs_path', sa.String(length=255), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=True),
    sa.Column('insurer_name', sa.String(length=100), nullable=True),
    sa.Column('policyholder_name', sa.String(length=100), nullable=True),
    sa.Column('property_address', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('total_premium', sa.Float(), nullable=True),
    sa.Column('coverage_details', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_policy_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_policy_data_policy_number'), ['policy_number'], unique=False)

    op.create_table('policy_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('document_source_filename', sa.String(length=255), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_chunks')
    with op.batch_alter_table('processed_policy_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_policy_data_policy_number'))

    op.drop_table('processed_policy_data')
    op.drop_table('policies')
    # ### end Alembic commands ###
