"""Add proactive fields to ProcessedPolicyData

Revision ID: 91f1fa4cba0e
Revises: 9db69ce29a3d
Create Date: 2025-06-19 13:23:28.358328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91f1fa4cba0e'
down_revision = '9db69ce29a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_policy_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('roof_age_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('property_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('last_proactive_analysis', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_policy_data', schema=None) as batch_op:
        batch_op.drop_column('last_proactive_analysis')
        batch_op.drop_column('property_features')
        batch_op.drop_column('roof_age_years')
        batch_op.drop_column('renewal_date')

    # ### end Alembic commands ###
