"""add feedback table

Revision ID: 949cd91067e4
Revises: d36c9f439f52
Create Date: 2025-07-22 14:12:33.281455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949cd91067e4'
down_revision = 'd36c9f439f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Boolean(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('policy_context', sa.JSON(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
