"""Add deductibles column to ProcessedPolicyData

Revision ID: 9db69ce29a3d
Revises: add_cosine_similarity
Create Date: 2025-06-16 15:35:58.810003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9db69ce29a3d'
down_revision = 'add_cosine_similarity'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_chunks', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=False)

    with op.batch_alter_table('processed_policy_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deductibles', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_policy_data', schema=None) as batch_op:
        batch_op.drop_column('deductibles')

    with op.batch_alter_table('policy_chunks', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=True)

    # ### end Alembic commands ###
