"""add_roofing_invoices_table

Revision ID: cb4f893989a0
Revises: 91f1fa4cba0e
Create Date: 2025-07-09 16:09:52.120109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4f893989a0'
down_revision = '91f1fa4cba0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roofing_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('roof_age_years', sa.Integer(), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('original_document_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['processed_policy_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roofing_invoices')
    # ### end Alembic commands ###
